

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>龙链 - 后台管理系统</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/public/layuiadmin/layui/css/layui.css" media="all">
    <style>.x-red{color: red;}</style>
</head>
<body>

<div class="layui-form" lay-filter="layuiadmin-form-role" id="layuiadmin-form-role" style="padding: 20px 30px 0 0;">
    <div class="layui-form-item">
        <label class="layui-form-label">理财期次：</label>
        <div class="layui-inline">
            <input type="date" name="period" lay-verify="required" placeholder="请输入期次" autocomplete="off" class="layui-input">
        </div>
        <div class="layui-inline"><span class="x-red">* 必填，如果不知道填写什么建议写期数，如：20181110</span></div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">理财币种：</label>
        <div class="layui-inline">
            <select name="currency_id">
                <?php foreach ($currency as $k=>$v): ?>
                <option value="<?=$v['id']?>"><?=$v['type']?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="layui-inline"><span class="x-red">* 必填</span></div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">利息币种：</label>
        <div class="layui-inline">
            <select name="x_currency_id">
                <?php foreach ($currency as $k=>$v): ?>
                    <option value="<?=$v['id']?>"><?=$v['type']?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="layui-inline"><span class="x-red">* 利息赠送到哪种类币</span></div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">理财模式：</label>
        <div class="layui-inline">
            <select name="ac_method">
                <option value="活期模式">活期模式</option>
                <option value="定期模式">定期模式</option>
            </select>
        </div>
        <div class="layui-inline"><span class="x-red">* 活期模式:可随时提取(扣取手续费)，定期模式:只能到期取</span></div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">手续费：</label>
        <div class="layui-inline">
            <input type="text" name="fee" lay-verify="required" placeholder="请输入手续费" autocomplete="off" class="layui-input">
        </div>
        <div class="layui-inline"><span class="x-red">% 活期模式,提前取本金手续费比例</span></div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">理财总量：</label>
        <div class="layui-inline">
            <input type="text" name="total" lay-verify="required" placeholder="请输入理财总量" autocomplete="off" class="layui-input">
        </div>
        <div class="layui-inline"><span class="x-red">* 必填，可理财的额度总量</span></div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">已理财量：</label>
        <div class="layui-inline">
            <input type="text" name="start_mun" lay-verify="required" placeholder="请输入已理财量" autocomplete="off" class="layui-input">
        </div>
        <div class="layui-inline"><span class="x-red">默认不设置，设置后会影响可理财的数量</span></div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">单次起购数量：</label>
        <div class="layui-inline">
            <input type="text" name="start_buy_mun" lay-verify="required" placeholder="请输入数量" autocomplete="off" class="layui-input">
        </div>
        <div class="layui-inline"><span class="x-red">* 必填，不能设置为0</span></div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">理财周期：</label>
        <div class="layui-inline">
            <input type="text" name="financial_cycle" lay-verify="required" placeholder="请输入理财周期" autocomplete="off" class="layui-input">
            <select name="time_type">
                <option value="分">分</option>
                <option value="时">时</option>
                <option value="日">日</option>
                <option value="月">月</option>
                <option value="年">年</option>
            </select>
        </div>
        <div class="layui-inline"><span class="x-red">* 分钟的理财奖励周期 1天 = 1440分钟 | 一个月 = 43200 分钟</span></div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">周期限额：</label>
        <div class="layui-inline">
            <input type="text" name="cycle_max" lay-verify="required" placeholder="请输入周期限额" autocomplete="off" class="layui-input">
        </div>
        <div class="layui-inline"><span class="x-red">* 必填，每个利息赠送周期内,最大可选购限制</span></div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">周期利息：</label>
        <div class="layui-inline">
            <input type="text" name="cycle_fee" lay-verify="required" placeholder="请输入周期利息" autocomplete="off" class="layui-input">
        </div>
        <div class="layui-inline"><span class="x-red">%</span></div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">开启时间 ：</label>
        <div class="layui-inline">
            <input type="date" name="start_time" autocomplete="off" class="layui-input">
        </div>
        <div class="layui-inline"><span class="x-red">* 必填</span></div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">结束时间 ：</label>
        <div class="layui-inline">
            <input type="date" name="end_time" autocomplete="off" class="layui-input">
        </div>
        <div class="layui-inline"><span class="x-red">* 必填</span></div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">状态</label>
        <div class="layui-inline">
            <select name="status">
                <option value="1">启用</option>
                <option value="0">禁用</option>
            </select>
        </div>
    </div>
    <div class="layui-form-item" style="float: right;">
        <button class="layui-btn" lay-submit lay-filter="LAY-user-role-submit" id="LAY-user-role-submit">提交</button>
        <button class="layui-btn" lay-reset lay-filter="LAY-user-role-close" id="LAY-user-role-close">取消</button>
    </div>
</div>

<script src="/public/layuiadmin/layui/layui.js"></script>
<script>
    layui.config({base: '/public/layuiadmin/'}).extend({index: 'lib/index'}).use(['index', 'form'], function(){
        var $ = layui.$,form = layui.form;
        form.on("submit(LAY-user-role-submit)",function (data) {
            let jsonstr = {
                period:data.field.period,
                currency_id:data.field.currency_id,
                x_currency_id:data.field.x_currency_id,
                ac_method:data.field.ac_method,
                fee:data.field.fee,
                total:data.field.total,
                start_mun:data.field.start_mun,
                start_buy_mun:data.field.start_buy_mun,
                financial_cycle:data.field.financial_cycle,
                time_type:data.field.time_type,
                cycle_max:data.field.cycle_max,
                cycle_fee:data.field.cycle_fee,
                start_time:data.field.start_time,
                end_time:data.field.end_time,
                status:data.field.status
            };
            var index2 = parent.layer.getFrameIndex(window.name); //获取窗口索引
            $.post("/adminactivity/addcbsx",jsonstr,function (msg) {
                if(msg == 1){
                    //发异步，把数据提交给php
                    layer.alert("添加持币生息成功", {icon: 6}, function() {
                        //关闭当前frame
                        parent.layer.close(index2);
                        // 可以对父窗口进行刷新
                        parent.location.reload();
                    });
                }else if(msg == 2){
                    layer.alert("该持币生息活动已存在，请重新输入")
                }else{
                    layer.alert("添加持币生息失败")
                }
            });
        });

        $("#LAY-user-role-close").on("click",function (data) {
            parent.layer.close(index2);
        });
    })
</script>
</body>
</html>