

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>龙链 - 后台管理系统</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/public/layuiadmin/layui/css/layui.css" media="all">
    <style>.x-red{color: red;}</style>
</head>
<body>

<div class="layui-form" lay-filter="layuiadmin-form-role" id="layuiadmin-form-role" style="padding: 20px 30px 0 0;">
    <div class="layui-form-item">
        <label class="layui-form-label">活动期次：</label>
        <div class="layui-inline">
            <input type="text" name="f_id" lay-verify="required" placeholder="请输入活动期次" autocomplete="off" class="layui-input">
        </div>
        <div class="layui-inline"><span class="x-red">* </span></div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">奖品BTC数量：</label>
        <div class="layui-inline">
            <input type="text" name="award_btc" lay-verify="required" placeholder="请输入奖品BTC数量" autocomplete="off" class="layui-input">
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">奖品USDT数量 ：</label>
        <div class="layui-inline">
            <input type="number" name="award_usdt" lay-verify="required" placeholder="请输入奖品USDT数量" autocomplete="off" class="layui-input">
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">奖品ETH数量 ：</label>
        <div class="layui-inline">
            <input type="number" name="award_eth" lay-verify="required" placeholder="请输入奖品ETH数量" autocomplete="off" class="layui-input">
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">奖品LBTH数量 ：</label>
        <div class="layui-inline">
            <input type="number" name="award_lbth" lay-verify="required" placeholder="请输入奖品LBTH数量" autocomplete="off" class="layui-input">
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">开启时间 ：</label>
        <div class="layui-inline">
            <input type="date" name="start_time" autocomplete="off" class="layui-input">
        </div>
        <div class="layui-inline"><span class="x-red">*</span></div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">结束时间 ：</label>
        <div class="layui-inline">
            <input type="date" name="end_time" autocomplete="off" class="layui-input">
        </div>
        <div class="layui-inline"><span class="x-red">*</span></div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">买单者：</label>
        <div class="layui-inline">
            <input type="number" name="payer" lay-verify="required" placeholder="请输入买单者名称" autocomplete="off" class="layui-input">
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">获胜者：</label>
        <div class="layui-inline">
            <input type="number" name="winner" lay-verify="required" placeholder="请输入买单获胜者" autocomplete="off" class="layui-input">
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">状态</label>
        <div class="layui-inline">
            <select name="status">
                <option value="0">启用</option>
                <option value="1">禁用</option>
            </select>
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">当前最大金额：</label>
        <div class="layui-inline">
            <input type="number" name="fomo_price" lay-verify="required" placeholder="请输入金额" autocomplete="off" class="layui-input">
        </div>
    </div>
    <div class="layui-form-item" style="float: right;">
        <button class="layui-btn" lay-submit lay-filter="LAY-user-role-submit" id="LAY-user-role-submit">提交</button>
        <button class="layui-btn" lay-reset lay-filter="LAY-user-role-close" id="LAY-user-role-close">取消</button>
    </div>
</div>

<script src="/public/layuiadmin/layui/layui.js"></script>
<script>
    layui.config({base: '/public/layuiadmin/'}).extend({index: 'lib/index'}).use(['index', 'form'], function(){
        var $ = layui.$,form = layui.form;
        form.on("submit(LAY-user-role-submit)",function (data) {
            let jsonstr = {
                f_id:data.field.f_id,
                award_btc:data.field.award_btc,
                award_usdt:data.field.award_usdt,
                award_eth:data.field.award_eth,
                award_lbth:data.field.award_lbth,
                start_time:data.field.start_time,
                end_time:data.field.end_time,
                payer:data.field.payer,
                winner:data.field.winner,
                status:data.field.status,
                fomo_price:data.field.fomo_price
            };
            var index2 = parent.layer.getFrameIndex(window.name); //获取窗口索引
            $.post("/adminactivity/addfomo",jsonstr,function (msg) {
                if(msg == 1){
                    //发异步，把数据提交给php
                    layer.alert("添加新币预售成功", {icon: 6}, function() {
                        //关闭当前frame
                        parent.layer.close(index2);
                        // 可以对父窗口进行刷新
                        parent.location.reload();
                    });
                }else if(msg == 2){
                    layer.alert("该新币预售活动已存在，请重新输入")
                }else{
                    layer.alert("添加新币预售失败")
                }
            });
        });

        $("#LAY-user-role-close").on("click",function (data) {
            parent.layer.close(index2);
        });
    });
</script>
</body>
</html>