

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>龙链 - 后台管理系统</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/public/layuiadmin/layui/css/layui.css" media="all">
</head>
<style>
    .layui-input-block{
        margin-left: 170px;
    }
    .layui-form-label{
        width: 124px;
    }
</style>
<body>

<div class="layui-form" lay-filter="layuiadmin-form-role" id="layuiadmin-form-role" style="padding: 20px 30px 0 0;">
    <div class="layui-form-item">
        <label class="layui-form-label">币种类型*</label>
        <div class="layui-input-block">
            <select name="currency_id">
                <?php foreach ($result["data"] as $k=>$v): ?>
                <option value="<?=$v['id']?>" <?php if($result["arrdata"]["currency_id"]==$v["id"]) echo "selected" ?>><?=$v["type"]?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">活动标题*</label>
        <div class="layui-input-block">
            <input type="text" name="title"  placeholder="请填写活动标题" autocomplete="off" class="layui-input" value="<?=$result["arrdata"]["title"]?>">
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">最少投币数量*</label>
        <div class="layui-input-block">
            <input type="text" name="least"  placeholder="最少投币数量" autocomplete="off" class="layui-input" value="<?=$result["arrdata"]["least"]?>">
            <input type="hidden" name="id" value="<?=$result["arrdata"]["id"]?>">
            <input type="hidden" name="page" value="<?=$result["page"]?>">
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">最多投币数量*</label>
        <div class="layui-input-block">
            <input type="text" name="maximum" placeholder="最多投币数量" autocomplete="off" class="layui-input" value="<?=$result["arrdata"]["maximum"]?>">
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">燃烧币种类型*</label>
        <div class="layui-input-block">
            <select name="x_currency_id">
                <?php foreach ($result["data"] as $k=>$v): ?>
                    <option value="<?=$v['id']?>" <?php if($result["arrdata"]["x_currency_id"]==$v["id"]) echo "selected" ?>><?=$v["type"]?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">每票燃烧多少币种*</label>
        <div class="layui-input-block">
            <input type="text" name="consume_number" placeholder="每票燃烧多少币种" autocomplete="off" class="layui-input" value="<?=$result["arrdata"]["consume_number"]?>">
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">规则*</label>
        <div class="layui-input-block">
            <textarea id="content"  style="display: none;" name="content"> <?=$result["arrdata"]["rule"]?></textarea>
        </div>
    </div>
    <div class="layui-form-item" style="float: right;">
        <button class="layui-btn" lay-submit lay-filter="LAY-user-role-submit" id="LAY-user-role-submit">提交</button>
        <button class="layui-btn" lay-reset lay-filter="LAY-user-role-close" id="LAY-user-role-close">取消</button>
    </div>
</div>

<script src="/public/layuiadmin/layui/layui.js"></script>
<script>
    layui.config({
        base: '/public/layuiadmin/' //静态资源所在路径
    }).extend({
        index: 'lib/index' //主入口模块
    }).use(['index', 'form','layedit'], function(){
        var $ = layui.$
            ,form = layui.form;
        var layedit = layui.layedit;
        layedit.set({uploadImage:{url:'/upload/edit',type:'post'}});
        var index = layedit.build('content',{hideTool:['face'], height: 350}); //建立编辑器
        var index2 = parent.layer.getFrameIndex(window.name); //先得到当前iframe层的索引
        form.on("submit(LAY-user-role-submit)",function (data) {
            let jsonstr = {
                currency_id:data.field.currency_id,
                least:data.field.least,
                maximum:data.field.maximum,
                id:data.field.id,
                title:data.field.title,
                page:data.field.page,
                x_currency_id:data.field.x_currency_id,
                consume_number:data.field.consume_number,
                content:layedit.getContent(index)
            };
            console.log(jsonstr.page)
            //发异步，把数据提交给php
            $.post("/ajax/editvote",jsonstr,function (msg) {
                if(msg == 1){
                    layer.msg("修改成功", {time:1000},function() {
                        //关闭当前frame
                        parent.layer.close(index2);
                        parent.layui.table.reload('LAY-user-back-manage',{page:{curr:jsonstr.page}});//主页代码，第一个参数为： 父页面的表格属性 id名
                    });
                }else if(msg == 2){
                    layer.msg("必填项不能为空", {time:1000})
                }else{
                    layer.msg("修改活动失败", {time:1000})
                }
            });
        });

        $("#LAY-user-role-close").on("click",function (data) {
            parent.layer.close(index2);
        });
    })

</script>
</body>
</html>