<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>龙链 - 后台管理系统</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/public/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/public/layuiadmin/style/admin.css" media="all">
</head>
<style>
    .pagination-large {
        overflow: hidden;
    }
</style>
<body>

<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-form layui-card-header layuiadmin-card-header-auto">
            <div class="layui-form-item">
                <div style="float: left;">
                    <div class="layui-inline">

                    </div>
                </div>
                <div style="float: right">
                    <div class="layui-inline">
                        <label class="layui-form-label">用户名</label>
                        <div class="layui-input-block">
                            <input type="text" name="username" placeholder="请输入用户名" autocomplete="off" class="layui-input">
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">币种</label>
                        <div class="layui-input-block">
                            <input type="text" name="currency_name" placeholder="请输入币种" autocomplete="off" class="layui-input">
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">消耗币种</label>
                        <div class="layui-input-block">
                            <input type="text" name="x_currency_name" placeholder="请输入消耗币种" autocomplete="off" class="layui-input">
                        </div>
                    </div>
                    <div class="layui-inline">
                        <button class="layui-btn layuiadmin-btn-admin" lay-submit lay-filter="LAY-user-back-search">
                            <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>

        <div class="layui-card-body">
            <table id="LAY-user-back-manage" lay-filter="LAY-user-back-manage"></table>
            <script type="text/html" id="status">
                {{#  if(d.freeze_status == d.unfreeze){ }}
                <div>完成</div>
                {{#  }else{ }}
                <div>解冻中</div>
                {{#  } }}
            </script>
        </div>
    </div>
</div>

<script src="/public/layuiadmin/layui/layui.js"></script>
<script>
    layui.config({base: '/public/layuiadmin/'}).extend({index: 'lib/index'}).use(['index', 'table', "layedit",'laydate'], function () {
        var $ = layui.$
            , form = layui.form
            , table = layui.table;
        table.render({
            elem: "#LAY-user-back-manage",
            url: "/ajax/list?table=newscoin",
            page: true,
            cols: [[
                {field: "id", width: 80, title: "ID", sort: !0},
                {field: "user_id", title: "用户ID"},
                {field: "title", title: "认购名称"},
                {field: "currency_name", title: "认购币种"},
                {field: "x_currency_name", title: "付款币种"},
                {field: "price", title: "认购单价"},
                {field: "num", title: "认购数量"},
                {title: "认购总额", toolbar: '<div>{{d.num * d.price}}</div>'},
                {field: "unfreeze", title: "解冻次数"},
                {title: "解冻间隔",toolbar: '<div>{{d.financial_cycle}} {{d.time_type}}</div>'},
                {field: "unfreeze", title: "解冻次数"},
                {field: "create_time", title: "认购时间", toolbar: '<div>{{ layui.util.toDateString(d.CreateTime*1000,"yyyy-MM-dd HH:mm:ss")}}</div>'},
                {field: "freeze_status", width: 180, title: "状态", toolbar: '#status'},
            ]],
            text: "对不起，加载出现异常！"
        });
        //事件
        var active = {}
        $('.layui-btn.layuiadmin-btn-admin').on('click', function () {
            var type = $(this).data('type');
            active[type] ? active[type].call(this) : '';
        });

        //监听搜索
        form.on('submit(LAY-user-back-search)', function (data) {
            var ctimes =data.field.start_time; //获取开始时间
            var etimes =data.field.end_time; //获取结束时间
            var key = "ctime";
            if(ctimes != "" && etimes != ""){//拼接时间选择
                var ctimes = Date.parse(ctimes+" 00:00:00");
                var etimes = Date.parse(etimes+" 23:59:59");
                var ctimes =ctimes/1000;
                var etimes =etimes/1000;
                var val = ctimes+" and "+"a.ctime <= "+etimes
                data.field[key] = val; //往对象里面赋值
            }else{
                data.field[key] = ""
            }
            delete data.field.start_time; //删除对象的值
            delete data.field.end_time;
            var field = data.field;
            table.reload('LAY-user-back-manage', {
                where: field
            });
        });

        var laydate = layui.laydate;
        //常规用法
        laydate.render({
            elem: '#test-laydate-normal-cn'
        });
        laydate.render({
            elem: '#test-laydate-normal-cn1'
        });

    });
</script>
</body>
<style>
    .layui-table-cell {
        height: 38px;
        line-height: 38px;
    }
</style
</html>

