<?php error_reporting(0); ?>
<!DOCTYPE html>
<html lang="en" style="background: #000000;">
<head>
    <meta charset="UTF-8">
    <meta name="viewport">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>龙链-NOT FILE 404</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta http-equiv="Refresh" content="3; url=/" />
    <link rel="stylesheet" href="/public/css/index.css">
    <link rel="stylesheet" href="/public/css/commonHead.css">
    <link rel="stylesheet" type="text/css" href="/public/css/login.css" />
</head>
<body>
    <!-- 主要内容 -->
    <div>
        <div style="border-bottom: 2px solid #131625">
            <!-- 导航栏部分 -->
            <?php load_view("inc/nav");?>
        </div>
    </div>
</body>
</html>