<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta data-n-head="true" data-hid="format-detection" name="format-detection" content="telephone=no">
    <meta data-n-head="true" http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta data-n-head="true" name="renderer" content="webkit">
    <title><?=$system['system']?>-我的资产</title>
    <link rel="stylesheet" href="/public/css/index.css">
    <link rel="stylesheet" href="/public/css/commonHead.css">
    <link rel="stylesheet" href="/public/css/index1.css">
    <!-- 当前页面内容样式 -->
    <link rel="stylesheet" href="/public/css/assetsIndex.css">
</head>

<body class="scroll">
<div id="app">
    <div class="box">
        <?php load_view("inc/nav");?>
        <!-- 合约账户 -->
        <div class="account contractAccount">
            <div class="topcontent ft20 fColor1"><span>资产</span></div>
            <?php load_view("inc/uc");?>
            <div class="rightcontent contentBK">
                <div>
                    <div class="header fColor1">
                        <p class="fl">
                            总资产折合：
                            <!-- data-v-67f8e012="" class="asset_num" -->
                            <span></span>205572.00</span> <span>CNY</span></p>
                        <!-- class="address" -->
                        <p class="fr right_text rightBut"><span>提币地址管理</span></p>
                    </div>
                    <div class="content fColor1 ft12">
                        <div class="content_top flex alcenter fColor2">
                            <p class="flex1 tc">币种<i></i></p>
                            <p class="flex1 tc">总数</p>
                            <p class="flex1 tc">可用</p>
                            <p class="flex1 tc">冻结</p>
                            <p class="flex1 tc">折合(CNY)</p>
                            <p class="flex1 tc">操作</p>
                        </div>
                        <ul class="content_ul">
                            <?php foreach ($coin as $k=>$v): ?>
                                <li class="li">
                                    <div class="content_li flex alcenter between">
                                        <!-- 币种部分 -->
                                        <p class="flex1 tc"><?=$v['type']?></p>
                                        <p class="flex1 tc"><?=$v['num']?></p>
                                        <p class="flex1 tc"><?=$v['available_balance']?></p>
                                        <p class="flex1 tc"><?=$v['freeze_balance']?></p>
                                        <p class="flex1 tc">0.00</p>
                                        <p class="flex1 tc operation" data-id="<?=$k?>">
                                            <span>充币</span>
                                            <span>提币</span>
                                            <span>记录</span>
                                        </p>
                                    </div>

                                    <div class="hide_div" style="display: none;">
                                        <!-- 点击充币 -->
                                        <div class="boxCon">
                                            <p class="fColor2 ft12">充币地址</p>
                                            <div class="mt50 mb50 clearfix">
                                                <img class="fl" style="width: 120px;height: 120px;display: block;" src="/public/imgae/anzhuo.png" alt="">
                                                <div class="fl">
                                                    <div>
                                                        <textarea cols="20" rows="10" readonly="readonly" id="biao1" class="copy ft14" style="border-radius: 5px;margin: 13px 0 27px 20px;padding: 10px;
                                            background: #fff;resize:none;height: 42px;width: 600px;font-family: none;"><?=$v['address']?></textarea>
                                                    </div>
                                                    <span id="copy" class="copy ft14" onClick="copyUrl2()" style="border-radius: 5px;margin-top: 20px;margin-left: 20px;padding: 10px;background: #fff;">复制</span>
                                                </div>
                                            </div>
                                            <div>
                                                <p class="ft12 fColor2 mb50">
                                                    查看
                                                    <span class="excharge_record">充币记录</span>跟踪状态
                                                </p>
                                            </div>
                                            <p class="ft12 fColor2 mb15">温馨提示</p>
                                            <ul class="tips_ul ft12 fColor2" style="list-style: disc inside;">
                                                <li class="tips_li" style="list-style: disc inside;">
                                                    请勿向上述地址充值任何非USDT资产，否则资产将不可找回。</li>
                                                <li class="tips_li" style="list-style: disc inside;">USDT充币仅支持simple send的方法，使用其他方法（send all）的充币暂时无法上账，请您谅解。</li>
                                            </ul>
                                        </div>
                                        <!-- 点击提币 -->
                                        <div class="boxCon" style="display: none;">
                                            <p class="fColor2 ft12 mb15">提币地址</p>
                                            <input type="text" class="address_inp fColor1 mb30">
                                            <p class="fColor2 ft12 mb15 flex between alcenter">
                                                <span>数量</span>
                                                <span>可用：<span class="use_num">0.00</span>BTC<span></span></span>
                                            </p>
                                            <label class="num_lab flex between mb30"><input type="text" placeholder="最小提币数量0.00" class="fColor1"> <span>BTC</span></label>
                                            <div class="flex mb50">
                                                <div class="left_inp_wrap flex1">
                                                    <p class="fColor2 ft12 mb15"><span>手续费</span> <span>3%</span></p> <label class="range_lab flex alcenter between"><span>0.00</span> <span>BTC</span></label>
                                                </div>
                                                <div class="right_inp_wrap flex1">
                                                    <p class="mb15"><span class="fColor2 ft12">到账数量</span></p>
                                                    <label class="get_lab flex alcenter between"><span>0.00</span> <span>BTC</span></label>
                                                </div>
                                            </div>
                                            <div class="flex">
                                                <div class="flex2">
                                                    <p class="ft12 fColor2 mb15">温馨提示</p>
                                                    <ul class="tips_ul ft12 fColor2" style="list-style: disc inside;">
                                                        <li class="tips_li" style="list-style: disc inside;">
                                                            请勿向上述地址充值任何非USDT资产，否则资产将不可找回。</li>
                                                        <li class="tips_li" style="list-style: disc inside;">USDT充币仅支持simple send的方法，使用其他方法（send all）的充币暂时无法上账，请您谅解。</li>
                                                    </ul>
                                                </div>
                                                <div class="flex1 tc"><button class="withdraw_btn">提币</button></div>
                                            </div>
                                        </div>
                                        <!-- 点击记录 -->
                                        <div class="rec-box boxCon" style="display: none;">
                                            <div class="rec-con">
                                                <div class="rec-title"><span>数量 </span> <span>记录</span> <span>时间</span></div>
                                                <ul class="rec-list">
                                                    <li><span>10000.00</span> <span>后台调节合约账户余额:SASAS</span> <span>2020-04-08 13:46:44</span></li>
                                                    <li><span>10000.00</span> <span>后台调节合约账户余额:</span> <span>2020-04-08 13:46:12</span></li>
                                                    <li><span>10000.00</span> <span>后台调节合约账户余额:</span> <span>2020-04-08 13:45:26</span></li>
                                                    <li><span>10000.00</span> <span>后台调节法币账户余额:</span> <span>2020-04-08 13:45:02</span></li>
                                                </ul>
                                                <p class="more">加载更多</p>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- 提币地址管理 -->
        <div class="account withdrawalAddress">
            <div class="topcontent ft20 ">
                <span class="white"><span class="baseColor">资产&gt;</span> 提币地址管理</span>
                <span class="white fr butReturn">&lt;&lt;返回</span>
            </div>
            <div class="content">
                <div>
                    <div class="contentBK fColor1  pdlr20 pdtb20 ft12">
                        <div class="flex alcenter">
                            <span class="w10 mr20">币种</span>
                            <span class="flex1 mr20">提币地址</span>
                            <span class="flex1">备注</span></div>
                        <div class="mt10">
                            <div class="flex alcenter">
                                <select name="" id="" class="w10 mr20 ">
                                    <option value="币种">币种</option>
                                    <option value="1">BTC</option>
                                    <option value="2">ETH</option>
                                    <option value="3">USDT</option>
                                </select>
                                <input placeholder="请输入提币地址" class="flex1 mr20">
                                <input placeholder="请输入备注" type="text" class="flex1 "></div>
                            <div class="add">
                                <div class="baseBtn">添加</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class=" mt15">
                    <div class="account_title ttBk white flex">
                        <div class="ml20">地址列表</div>
                    </div>
                    <div class="contentBK fColor1  pdlr20 pdtb20 ft12">
                        <div class="flex alcenter">
                            <span class="flex1">币种</span>
                            <span class="flex1">提币地址</span>
                            <span class="flex1">备注</span>
                            <span class="flex1">操作</span>
                        </div>
                        <div class="mt10">
                            <div class="flex alcenter">
                                <span class="flex1"> ETH</span>
                                <span class="flex1">0x61010e9524f84879ea210eafb97fe0a0acfc6b0f</span>
                                <span class="flex1">imeth</span>
                                <span class="flex1">删除</span>
                            </div>
                        </div>
                        <!---->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
<div class="layui-layer-move"></div>
</body>

</html>
<script type="text/javascript" src="/public/layer/jquery-1.9.1.min.js"></script>
<script type="text/javascript" src="/public/layer/layer.js"></script>
<script type="text/javascript">
    $(function() {
        $(".content_ul").on("click", "li div .operation span", function() {
            var id = Number($(this).parent().attr("data-id"));
            var _index = $(this).index();
            $(".content_ul .li .hide_div").hide();
            $(".content_ul .li .hide_div .boxCon").hide();
            $(".content_ul .li").eq(id).children(".hide_div").show();
            $(this).parent().parent().next('div').find(".boxCon").eq(_index).show();
        });
        $(".rightBut").click(function() {
            $(".contractAccount").hide();
            $(".withdrawalAddress").show();
        });
        $(".butReturn").click(function() {
            $(".contractAccount").show();
            $(".withdrawalAddress").hide();
        });
    })

    function copyUrl2() {
        var Url2 = document.getElementById("biao1");
        Url2.select();
        document.execCommand("Copy");
        layer.msg("复制成功");
    }
</script>