<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta data-n-head="true" data-hid="format-detection" name="format-detection" content="telephone=no">
    <meta data-n-head="true" http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta data-n-head="true" name="renderer" content="webkit">
    <title><?=$system['system']?>-我的资产</title>
    <link rel="stylesheet" href="/public/css/index.css">
    <link rel="stylesheet" href="/public/css/commonHead.css">
    <link rel="stylesheet" href="/public/css/index1.css">
    <!-- 当前页面内容样式 -->
    <link rel="stylesheet" href="/public/css/assetsIndex.css">
    <style>
        .rec-con ul li:nth-of-type(2n-1) {
            background: #171c2c !important;
            height: 45px;
            border: none;
        }
        .rec-con ul li:nth-of-type(2n) {
            background: #191E35 !important;
            height: 45px;
            border: none;
        }
    </style>
</head>

<body class="scroll">
    <div id="app">
        <div class="box">
            <?php load_view("inc/nav");?>
            <!-- 合约账户 -->
            <div class="account contractAccount">
                <div class="topcontent ft20 fColor1"><span>资产</span></div>
                <?php load_view("inc/uc");?>
                <div class="rightcontent contentBK">
                    <div>
                        <div class="header fColor1 navList" style="background: rgba(29,36,54,1);display: flex;">
                            <p class="fl"><span class="activeList">充值</span></p>
                            <p class="fl"><span class="">提现</span></p>
                            <p class="fl"><span class="">划转</span></p>
                            <p class="fl"><span class="">分红</span></p>
                            <p class="fl"><span class="">投币</span></p>
                            <p class="fl"><span class="">矿池</span></p>
                            <p class="fl"><span class="">拍卖</span></p>
                            <p class="fl"><span class="">新币</span></p>
                            <p class="fl"><span class="">还币</span></p>
                            <p class="fl"><span class="">法币</span></p>
                            <p class="fl"><span class="">币币</span></p>
                            <p class="fl"><span class="">合约</span></p>
                        </div>
                        <div class="content fColor1 ft12">
                            <ul class="content_ul">
                                <li class="li">
                                    <div class="hide_div">
                                        <!-- 点击记录 -->
                                        <div class="rec-box boxCon">
                                            <div class="rec-con">
                                                <div class="rec-title">
                                                    <span class="span">id</span>
                                                    <span class="span">类型</span>
                                                    <span class="span1">描述信息</span>
                                                    <span class="span">金额</span>
                                                    <span class="span">币种名称</span>
                                                    <span class="span2">时间</span>
                                                </div>
                                                <ul class="rec-list">
                                                    <?php foreach($user_log as $k=>$v): ?>
                                                    <li>
                                                        <span class="span"><?=$v['id']?></span>
                                                        <span class="span"><?=$v['type']?></span>
                                                        <span class="span1"><?=$v['info']?></span>
                                                        <span class="span"><?=$v['num']?></span>
                                                        <span class="span"><?=$v['currency_name']?></span>
                                                        <span class="span2"><?=date("Y-m-d H:i:s",$v['create_time'])?></span>
                                                    </li>
                                                    <?php endforeach; ?>
                                                </ul>
                                                <p class="more">加载更多</p>
                                            </div>
                                        </div>
                                    </div>
                                </li>

                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    <div class="layui-layer-move"></div>
</body>
<script type="text/javascript" src="/public/layer/jquery-1.9.1.min.js"></script>
<script type="text/javascript" src="/public/layer/layer.js"></script>
</html>
<style>
    .hide_div {
        padding: 0;
        border: none;
    }
    
    .rec-box .rec-con {
        margin: 10px 0;
        padding: 0;
    }
    
    .navList P {
        flex: 1;
        text-align: center;
        cursor: pointer;
    }
    
    .navList P span {
        padding: 8px 5px;
        border-bottom: 2px solid #0E2648;
        color: rgba(255,255,255,0.5);
    }
    
    .activeList {
        color: #008cf8 !important;
        border-bottom: 2px solid #008cf8 !important;
    }
    .rec-box .rec-con .span{
        flex: 1;
        text-align: center;
        /*line-height: 3;*/
    }
    .rec-box .rec-con .span1{
        flex: none;
        width: 350px;
        /*overflow: hidden;*/
        display: block;
        /*white-space: nowrap;*/
        /*text-overflow: ellipsis;*/
        /*overflow: hidden;*/
        /*word-break: break-all;*/
    }
    .rec-box .rec-con .span2{
        flex: none;
        width: 150px;
        display: block;
    }
    .content_ul{
        padding: 0 !important;
    }
</style>
<script type="text/javascript" src="/public/js/jquery-3.1.1.min.js"></script>
<script type="text/javascript" src="/public/js/public.js"></script>
<script type="text/javascript">
    $(".navList p").click(function() {
        var index = $(this).index();
        var type = $(this).find("span").text();
        $(".navList p span").removeClass("activeList");
        $(".navList p").eq(index).children().addClass("activeList");
        ajax_http("post","/uc/transactions",{type:type},function(msg){
            $(".rec-list").empty();
            var str = "";
            for(item of msg){
                str += "<li>";
                str += "<span class='span'>"+item.id+"</span>";
                str += "<span class='span'>"+item.type+"</span>";
                str += "<span class='span1'>"+item.info+"</span>";
                str += "<span class='span'>"+item.num+"</span>";
                str += "<span class='span'>"+item.currency_name+"</span>";
                str += "<span class='span2'>"+formatDate(item.create_time*1000)+"</span>";
                str += "</li>";
            }
            $(".rec-list").html(str);
        },"json");
    })

    function formatDate(date) {
        var date = new Date(date);
        var YY = date.getFullYear() + '-';
        var MM = (date.getMonth() + 1 < 10 ? '0' + (date.getMonth() + 1) : date.getMonth() + 1) + '-';
        var DD = (date.getDate() < 10 ? '0' + (date.getDate()) : date.getDate());
        var hh = (date.getHours() < 10 ? '0' + date.getHours() : date.getHours()) + ':';
        var mm = (date.getMinutes() < 10 ? '0' + date.getMinutes() : date.getMinutes()) + ':';
        var ss = (date.getSeconds() < 10 ? '0' + date.getSeconds() : date.getSeconds());
        return YY + MM + DD +" "+hh + mm + ss;
    }
</script>