

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>龙链 - 后台管理系统</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/public/layuiadmin/layui/css/layui.css" media="all">
</head>
<body>

<div class="layui-form" lay-filter="layuiadmin-form-role" id="layuiadmin-form-role" style="padding: 20px 30px 0 0;">
    <div class="layui-form-item">
        <label class="layui-form-label">ICON</label>
        <div class="layui-input-block">
            <button type="button" class="layui-btn" id="test1"><i class="layui-icon">&#xe67c;</i>上传图片</button>
            <img src="<?=$result['icon']?>" width="50" height="50" />
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">币种</label>
        <div class="layui-input-block">
            <input type="text" name="type" lay-verify="required" autocomplete="off" class="layui-input" value="<?=$result['type']?>">
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">状态</label>
        <div class="layui-input-block">
            <input type="checkbox" name="status" lay-text="ON|OFF" value="<?=$result['status']?>" lay-skin="switch" <?php if($result['status']){echo 'checked';}?>>
        </div>
    </div>
    <div class="layui-form-item" style="float: right;">
        <button class="layui-btn" lay-submit lay-filter="LAY-user-role-submit" id="LAY-user-role-submit">提交</button>
        <button class="layui-btn" lay-reset lay-filter="LAY-user-role-close" id="LAY-user-role-close">取消</button>
    </div>
</div>

<script src="/public/layuiadmin/layui/layui.js"></script>
<script>
    layui.config({
        base: '/public/layuiadmin/' //静态资源所在路径
    }).extend({
        index: 'lib/index' //主入口模块
    }).use(['index', 'form','upload'], function(){
        var $ = layui.$
            ,form = layui.form;
        var upload = layui.upload;
        var fileurl;
        //执行实例
        var uploadInst = upload.render({
            elem: '#test1' //绑定元素
            ,url: '/upload/index' //上传接口
            ,done: function(res){
                fileurl = res.data
            }
            ,error: function(){
                fileurl = null
            }
        });
        var index2 = parent.layer.getFrameIndex(window.name); //获取窗口索引
        form.on("submit(LAY-user-role-submit)",function (data) {
            let jsonstr = {
                id:"<?=$result['id']?>",
                type:data.field.type,
                status:data.field.status,
                icon:fileurl
            };
            $.post("/ajax/editcurrency",jsonstr,function (msg) {
                if(msg == 1){
                    //发异步，把数据提交给php
                    layer.alert("修改币种成功", {icon: 6}, function() {
                        //关闭当前frame
                        parent.layer.close(index2);
                        // 可以对父窗口进行刷新
                        parent.location.reload();
                    });
                }else{
                    layer.alert("修改币种失败")
                }
            });
        });

        $("#LAY-user-role-close").on("click",function (data) {
            parent.layer.close(index2);
        });
    })
</script>
</body>
</html>