

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>龙链 - 后台管理系统</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/public/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/public/layuiadmin/style/admin.css" media="all">
</head>
<body>

<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-form layui-card-header layuiadmin-card-header-auto">
            <div class="layui-form-item">
                <div style="float: left;">

                </div>
                <div style="float: right">
                    <div class="layui-inline">
                        <label class="layui-form-label">用户ID</label>
                        <div class="layui-input-block">
                            <input type="text" name="loginname" placeholder="请输入id" autocomplete="off" class="layui-input">
                        </div>
                    </div>
                    <div class="layui-inline">
                        <button class="layui-btn layuiadmin-btn-admin" lay-submit lay-filter="LAY-user-back-search">
                            <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <div class="layui-card-body">
            <table id="LAY-user-back-manage" lay-filter="LAY-user-back-manage"></table>
            <div class="layui-card-body">
                <table class="layui-table  layui-form" lay-filter="layuiadmin-form-role" id="layuiadmin-form-role">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>用户ID</th>
                        <th>倍数</th>
                        <th>手数</th>
                        <th>类型</th>
                        <th>保证金</th>
                        <th>手续费</th>
                        <th>市价</th>
                        <th>挂单时间</th>
                        <th>状态</th>
                        <th>交易时间</th>
                        <th>平仓时间</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody id="coin">
                    <?php foreach($result as $key=>$value): ?>
                        <tr>
                            <th><?=$value['id']?></th>
                            <th><?=get_user_name($value['u_id'])?></th>
                            <th><?=$value['multiple']?></th>
                            <th><?=$value['lots']?></th>
                            <th><?=$value['type']?></th>
                            <th><?=$value['margin']?></th>
                            <th><?=$value['fee']?></th>
                            <th><?=$value['market_price']?></th>
                            <th><?=date("Y-m-d H:i:s",$value['create_time'])?></th>
                            <?php
                            switch ($value['status']){
                                case 0 : $str = "挂单中";break;
                                case 1 : $str = "交易中";break;
                                case 2 : $str = "平仓中";break;
                                case 3 : $str = "已平仓";break;
                                case 4 : $str = "已撤单";break;
                            }
                            ?>
                            <th><?=$str?></th>
                            <th><?=date("Y-m-d H:i:s",$value['transaction_time'])?></th>
                            <th><?=date("Y-m-d H:i:s",$value['handle_time'])?></th>
                            <th class="td-manage">
                                <a title="删除" data-id="<?=$value['id']?>" class="layui-btn  layui-btn-danger del">删除</a>
                            </th>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script src="/public/layuiadmin/layui/layui.js"></script>
<script>
    layui.config({base: '/public/layuiadmin/'}).extend({index: 'lib/index'}).use(['index'], function(){
        var $ = layui.$;
        //事件
        var active = {};
        $('.layui-btn.layuiadmin-btn-admin').on('click', function(){
            var type = $(this).data('type');
            active[type] ? active[type].call(this) : '';
        });
        $('#coin').on('click','tr .td-manage .del',function () {
            var id = $(this).attr("data-id");
            layer.confirm('确认要删除吗？',function(index){
                $.post("/ajax/del",{id:id,table:'heyue_data'},function (msg) {
                    if(msg == 1){
                        layer.msg("已删除");
                        setTimeout(()=> location.reload(),1000)
                    }else{
                        layer.msg("操作失败");
                    }
                });
            });
        });
    });
</script>
</body>
</html>

