

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>龙链 - 后台管理系统</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/public/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/public/layuiadmin/style/admin.css" media="all">
</head>
<body>

<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-form layui-card-header layuiadmin-card-header-auto">
            <div class="layui-form-item">
                <div style="float: left;">
                    <div class="layui-inline">

                    </div>
                </div>
                <div style="float: right">
                    <div class="layui-inline">
                        <label class="layui-form-label">标题</label>
                        <div class="layui-input-block">
                            <input type="text" name="loginname" placeholder="请输入标题" autocomplete="off" class="layui-input">
                        </div>
                    </div>
                    <div class="layui-inline">
                        <button class="layui-btn layuiadmin-btn-admin" lay-submit lay-filter="LAY-user-back-search">
                            <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>

        <div class="layui-card-body">

            <table id="LAY-user-back-manage" lay-filter="LAY-user-back-manage"></table>

            <script type="text/html" id="build_status">
                {{#  if(d.build_status==1){ }}
                    <span style="color: #00A000">申请成功</span>
                {{#  } else { }}
                    <span style="color: #01AAED">申请失败</span>
                {{#  } }}
            </script>
            <script type="text/html" id="status">
                {{# if(d.status==0){ }}
                    <span style="color: #9eb5ca">未处理</span>
                {{# }else if(d.status==1){ }}
                    <span style="color: #00A000">已处理</span>
                {{# }else if(d.status==2){ }}
                    <span style="color: #f43530">已退款</span>
                {{# }else{ }}
                    <span style="color: #40a9ff">手动待处理</span>
                {{# } }}
            </script>
            <script type="text/html" id="create_time">
                <div>{{ layui.util.toDateString(d.createDate, "yyyy-MM-dd HH:mm:ss") }}</div>
            </script>
            <script type="text/html" id="auto_address">
                {{#  if(d.auto_address==1){ }}
                    <span style="color: #01AAED">手动处理</span>
                {{#  } else { }}
                    <span style="color: #00A000">自动处理</span>
                {{#  } }}
            </script>
            <script type="text/html" id="table-useradmin-admin">
                <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del"><i class="layui-icon layui-icon-delete"></i>删除</a>
            </script>
        </div>
    </div>
</div>

<script src="/public/layuiadmin/layui/layui.js"></script>
<script>
    layui.config({base: '/public/layuiadmin/'}).extend({index: 'lib/index'}).use(['index', 'table',"layedit"], function(){
        var $ = layui.$
            ,form = layui.form
            ,table = layui.table;
        table.render({
            elem: "#LAY-user-back-manage",
            url: "/ajax/list?table=withdraw",
            page: true,
            cols: [[
                {type: "checkbox", fixed: "left"},
                {field: "id", width: 80, title: "ID", sort: !0},
                {field: "u_id", title: "用户ID"},
                {field: "currency", title: "币种"},
                {field: "token_num", title: "金额"},
                {field: "order_no", title: "订单号"},
                {field: "build_status", title: "申请状态", toolbar: '#build_status'},
                {field: "address", title: "提现地址"},
                {field: "status", title: "提现状态", toolbar: '#status'},
                {field: "create_time", title: "提现时间", toolbar: '#create_time'},
                {field: "auto_address", title: "处理方式", toolbar: '#auto_address'},
                {title: "操作", width: 150, align: "center", fixed: "right", toolbar: "#table-useradmin-admin"}]
            ],
            text: "对不起，加载出现异常！"
        }),table.on("tool(LAY-user-back-manage)", function (e) {
            e.data;
            if ("del" === e.event) layer.prompt({formType: 1, title: "敏感操作，请验证口令"}, function (t, i) {
                layer.close(i), layer.confirm("确定删除此记录？", function (t) {
                    var id = e.data.id;
                    $.post("/ajax/del",{id:id,table:'withdraw'},function (msg) {
                        if(msg == 1){
                            e.del(), layer.close(t)
                        }else{
                            layer.msg("操作失败");
                            layer.close(t)
                        }
                    });
                })
            })
        });
        //监听搜索
        form.on('submit(LAY-user-back-search)', function(data){
            var field = data.field;
            //执行重载
            table.reload('LAY-user-back-manage', {
                where: field
            });
        });
    });
</script>
</body>
</html>

