<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>网站设置</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/public/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/public/layuiadmin/style/admin.css" media="all">
</head>
<body>

<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">系统设置</div>
                <div class="layui-card-body" pad15>

                    <div class="layui-form" wid100 lay-filter="">
                        <div class="layui-form-item">
                            <label class="layui-form-label">一级代理奖励</label>
                            <div class="layui-input-block">
                                <input type="text" name="grade1" value="<?=$result['grade1'] ?>" class="layui-input">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">二级代理奖励</label>
                            <div class="layui-input-block">
                                <input type="text" name="grade2" value="<?=$result['grade2']?>" class="layui-input">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">三级代理奖励</label>
                            <div class="layui-input-block">
                                <input type="text" name="grade3" value="<?=$result['grade3']?>" class="layui-input">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">四级代理奖励</label>
                            <div class="layui-input-block">
                                <input type="text" name="grade4" value="<?=$result['grade4']?>" class="layui-input">
                            </div>
                        </div>
                        <div class="layui-form-item layui-form-text">
                            <label class="layui-form-label">五级代理奖励</label>
                            <div class="layui-input-block">
                                <input type="text" name="grade4" value="<?=$result['grade5']?>" class="layui-input">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <div class="layui-input-block">
                                <button class="layui-btn" lay-submit lay-filter="set_website" id="set_website">确认保存</button>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<script src="/public/layuiadmin/layui/layui.js"></script>
<script>

    layui.config({
        base: '/public/layuiadmin/' //静态资源所在路径
    }).extend({
        index: 'lib/index' //主入口模块
    }).use(['index', 'form'], function () {
        var $ = layui.$
            , form = layui.form;
        form.on("submit(set_website)", function (data) {
            let jsonstr = {
                grade1: data.field.grade1,
                grade2: data.field.grade2,
                grade3: data.field.grade3,
                grade4: data.field.grade4,
                grade5: data.field.grade5
            };
            $.post("/ajax/reward", jsonstr, function (msg) {
                if (msg == 1) {
                    //发异步，把数据提交给php
                    layer.alert("操作成功", {icon: 6}, function () {
                        // 对窗口进行刷新
                        location.reload();
                    });
                } else if (msg == 2) {
                    layer.alert("该内容已经存在，请重新输入")
                } else {
                    layer.alert("操作成功")
                }
            });
        });
    });
</script>
</body>
</html>
<style>
    .layui-anim.layui-icon {
        margin: -8px 0 0 8px;
    }
</style>