<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta data-n-head="true" data-hid="format-detection" name="format-detection" content="telephone=no">
    <meta data-n-head="true" http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta data-n-head="true" name="renderer" content="webkit">
    <title><?=$system['system']?>-首页</title>
<!--    <link rel="icon" type="image/x-icon" href="/public/imgae/anzhuo.png">-->
    <link rel="stylesheet" href="/public/css/index.css" >
    <link rel="stylesheet" href="/public/css/commonHead.css">
    <link rel="stylesheet" href="/public/css/swiper.min.css">
    <link rel="stylesheet" href="/public/css/index1.css">
</head>
<body class="scroll">
    <div id="app">
        <div class="indexBlackes" style="background: #000000;">
            <!-- 导航栏部分 -->
            <?php load_view("inc/nav");?>
            <!-- 轮播图 -->
            <div class="rotationChart">
                <div class="swiper-container">
                    <div class="swiper-wrapper">
                        <?php foreach ($result["banner"] as $k =>$v): ?>
                        <div class="swiper-slide">
                            <div style="background: url('<?=$v ?>') no-repeat;width: 100%;height: 100%;background-size: 100% 100%;"></div>
                        </div>
                        <?php endforeach; ?>
                    </div>
                    <!-- Add Pagination -->
                    <div class="swiper-pagination"></div>
                </div>
            </div>
             <!-- 多个币种 -->
             <div id="container">
                <!-- <div class="boxCon fl" style="background: url(./imgae/increase1.png);background-repeat: no-repeat;background-size: 100% 100%;">
                    <div class="clearfix currency">
                        <span class="currencyLeft fl">USDT</span>
                        <span class="currencyRight fr actGreen">-0.07%</span>
                    </div>
                    <div class="clearfix amount">
                        <span class="amountLeft fl actGreen">2.9645</span>
                        <span class="amountRight fr">24h量</span>
                    </div>
                </div> -->
                <div class="boxCon fl" style="background: url(./imgae/increase1.png);background-repeat: no-repeat;background-size: 100% 100%;">
                    <div class="clearfix currency"><span class="currencyLeft fl">USDT</span><span class="currencyRight fr actGreen">-0.07%</span> </div>
                    <div class="clearfix amount">
                        <div class="clearfix amount"><span class="amountLeft fl actGreen">2.9645</span><span class="amountRight fr">2455h量</span> </div>
                    </div>
                </div>
                <div class="boxCon fl" style="background: url(./imgae/reduce1.png);background-repeat: no-repeat;background-size: 100% 100%;">
                    <div class="clearfix currency"><span class="currencyLeft fl">USDT</span><span class="currencyRight fr actGreen">-0.07%</span> </div>
                    <div class="clearfix amount">
                        <div class="clearfix amount"><span class="amountLeft fl actGreen">2.9645</span><span class="amountRight fr">2455h量</span> </div>
                    </div>
                </div>
            </div>
            <!--  交易所 -->
            <div class="platform">
                <div class="platformList">
                    <div class="title">—— 交易所真实交易大厅 ——</div>
                    <div class="describe">为全球超过130个国家的数千万用户提供安全、可信赖的数字资产交易及资产管理服务</div>
                    <div class="listBox">
<!--                        <div style="font-size: 20px;text-align: center;">多年服务经验,资产安全管理,最新高性能智能储存技术,</div>-->
                        <div class="useTitle" style="background: #1D2436;height: 55px;line-height: 55px;overflow: hidden;padding: 0 10px;border-radius: 5px 5px 0 0;">
                            <div class="text actoveUser">USDT</div>
                            <div class="text">BTC</div>
                            <div class="text">ETH</div>
                        </div>
                        <div class="content fColor1 ft12">
                            <ul class="content_ul">
                                <li class="li">
                                    <div class="hide_div">
                                        <!-- 点击记录 -->
                                        <div class="rec-box boxCon">
                                            <div class="rec-con">
                                                <div class="rec-title" style="background: #131625;border-bottom: 1px dashed #2D2D2F;">
                                                    <span class="span">币种</span>
                                                    <span class="span">最新价</span>
                                                    <span class="span">交易量</span>
                                                    <span class="span1">涨幅榜</span>
                                                    <span class="span2">操作</span>
                                                </div>
                                                <ul class="rec-list" id="rec-list"></ul>
                                                <!--                                            <p class="more">加载更多</p>-->
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
<!--                    <div class="exchange"></div>-->
                </div>
            </div>
            <!-- 交易平台 -->
            <div class="platform" style="padding-bottom: 20px;">
                    <div class="platformList">
                        <div class="title">—— 全球领先的数字资产交易平台 ——</div>
                        <div class="describe">多年服务经验,资产安全管理,最新高性能智能储存技术,智能加密防止篡改</div>
                        <div class="list">
                            <ul class="clear">
                                <li class="fl" style="margin-left: 0px;">
                                    <div class="img1"></div>
                                    <div class="textTitle">安全可信赖</div>
                                    <div class="text">五年数字资产金融服务经验</div>
                                    <div class="text">专业分布式架构</div>
                                    <div class="text">和防DDOS攻击系统</div>
                                </li>
                                <li class="fl">
                                    <div data-v-443b1e92="" class="img1 img2"></div>
                                    <div class="textTitle">全球生态平衡</div>
                                    <div class="text">多个国家设立本土化交易</div>
                                    <div class="text">服务中心,打造多业务形态</div>
                                    <div class="text">为一体的区块链生态圈</div>
                                </li>
                                <li class="fl">
                                    <div data-v-443b1e92="" class="img1 img3"></div>
                                    <div class="textTitle">交易安全稳定</div>
                                    <div class="text">高性能技术架构,多级数据灾备</div>
                                    <div class="text">1:1准备金仓储,不仅仅是交易所</div>
                                    <div class="text">也是您的资产安全管理钱包</div>
                                </li>
                                <li class="fl">
                                    <div data-v-443b1e92="" class="img1 img4"></div>
                                    <div class="textTitle">容贵宾级客户服务</div>
                                    <div class="text">7X24X365天及时响应1V1</div>
                                    <div class="text"> 客服服务！为您的数字资产</div>
                                    <div class="text">安全交易保驾护航！</div>
                                </li>
                                <li class="fl">
                                    <div data-v-443b1e92="" class="img1 img5"></div>
                                    <div class="textTitle">信息加密防篡改</div>
                                    <div class="text">区块链技术，保护您的交易</div>
                                    <div class="text">信息，保留您的交易数据</div>
                                    <div class="text">智能加密，自动屏蔽信息篡改</div>
                                </li>
                            </ul>
                        </div>
                    </div>
            </div>
            <!-- 大图区块链 -->
            <div class="Blockchain">
                <div class="but">点击了解更多</div>
            </div>
            <!--  交易所 -->
            <div class="platform">
                <div class="platformList">
                    <div class="title">—— 交易所真实交易大厅 ——</div>
                    <div class="describe">为全球超过130个国家的数千万用户提供安全、可信赖的数字资产交易及资产管理服务</div>
                    <div class="exchange"></div>
                </div>
            </div>
            <!-- 交易所后台数据圆 -->
            <div class="exchangeData"></div>
             <!-- 终端模块 -->
<!--            <div class="platform" style="background: url(/public/imgae/back.png) no-repeat center;background-size: auto auto;">-->
<!--                <div class="platformList">-->
<!--                    <div class="title">—— 随时随地 多平台终端交易 ——</div>-->
<!--                    <div class="describe">覆盖iOS、Android、Windows、Mac多个平台，支持全业务功能</div>-->
<!--                    <div class="terminal"></div>-->
<!--                </div>-->
<!--            </div>-->
            <!-- 交易平台 -->
<!--            <div class="tradingPlatform"></div>-->
            <!-- q区块链最新资讯 -->
            <div class="platform" style="background: url(/public/imgae/informationBack.png) no-repeat center;background-size: auto auto;">
                <div class="platformList">
                    <div class="title">——  区块链最新行业资讯  ——</div>
                    <div class="describe">无形胜有形，链接未来的区块链已逐渐成为不可摧的风险转移对象</div>
                    <!-- <div class="exchange"></div> -->
                    <div class="information">
                        <ul class="clearfix">
                            <li class="fl li" style="margin-left: 0px;">
                               <div class="titles clearfix">
                                 <div class="fl">行业资讯</div>
                                 <div class="fr" style="color: #54555C;"><a href="#">查看更多</a></div>
                               </div>
                               <ul class="ul" style="padding: 20px 0 20px 30px;">
                                  <?php foreach($result['hyzx'] as $k1=>$v1): ?>
                                     <li class="li1" onclick="window.location.href='/Index/news?id=<?=$v1['id']?>&lang=zh'"><?=$v1['title']?></li>
                                  <?php endforeach; ?>
                               </ul>
                            </li>
                            <li class="fl li" style="margin-left: 0px;">
                                <div class="titles clearfix">
                                  <div class="fl">财经资讯</div>
                                  <div class="fr" style="color: #54555C;"><a href="#">查看更多</a></div>
                                </div>
                                <ul class="ul" style="padding: 20px 0 20px 30px;">
                                    <?php foreach($result['cjzx'] as $k2=>$v2): ?>
                                        <li class="li1" onclick="window.location.href='/Index/news?id=<?=$v2['id']?>&lang=zh'"><?=$v2['title']?></li>
                                    <?php endforeach; ?>
                                </ul>
                             </li>
                             <li class="fl li" style="margin-left: 0px;">
                                <div class="titles clearfix">
                                  <div class="fl">国际资讯</div>
                                  <div class="fr" style="color: #54555C;"><a href="#">查看更多</a></div>
                                </div>
                                <ul class="ul" style="padding: 20px 0 20px 30px;">
                                    <?php foreach($result['gjzx'] as $k3=>$v3): ?>
                                        <li class="li1" onclick="window.location.href='/Index/news?id=<?=$v3['id']?>&lang=zh'"><?=$v3['title']?></li>
                                    <?php endforeach; ?>
                                </ul>
                             </li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- 底部-->
            <?php load_view("inc/footer");?>
        </div>
    </div>
</body>
</html>
<script type="text/javascript" src="/public/js/jquery-3.1.1.min.js"></script>

<script src="/public/js/public.js">
</script>
<script type="text/javascript" src="/public/js/swiper.min.js"></script>
<script>
    var swiper = new Swiper('.swiper-container', {
        pagination: '.swiper-pagination',
        paginationClickable: true,
        spaceBetween: 0,
        autoplay: 2000,
        speed: 1000,
        loop: true
    });

    $(function() {
        list();
        ajaxdata();
    }, )

//    ....
    $(".useTitle .text").click(function () {
//        var $(this).index()
        $(this).addClass('actoveUser').siblings().removeClass('actoveUser')
    })
    function list() {
        ajax_http("post","/trade/cointype",{size:8}, function(success) {
            if (success.code == 200) {
                //var num = Math.floor(Math.random() * 10 + 1);
                var num = 1;
                var html = '';
                for (const [i, v]  of  success.data.entries()) {
                    var reduce = '';
                    var actGreen = '';
                    if (v.change_percent < 0) {
                        reduce = '/public/imgae/reduce' + num + '.png';
                        actGreen = 'actRed';
                    } else {
                        reduce = '/public/imgae/increase' + num + '.png';
                        actGreen = 'actGreen';
                    }
                    html += '<div class="boxCon fl" style="background: url(' + reduce + ');background-repeat: no-repeat;background-size: 100% 100%;">' +
                        '<div class="clearfix currency">' +
                        '<span class="currencyLeft fl"><a href="/trade/index?type=trade&market='+ v.co_name +'_usdt&lang=zh">' + v.name + '</a></span>' +
                        '<span class="currencyRight fr ' + actGreen + '">' + v.change_percent + '%</span>' +
                        '</div><div class="clearfix amount">' +
                        '<span class="amountLeft fl ' + actGreen + '">' + v.current_price_usd + '</span>' +
                        '<span class="amountRight fr">24h量</span>' +
                        '</div>' +
                        '</div> ';
                }
                $("#container").html(html);
            }
        },"json")
    }
    function ajaxdata() {
        ajax_http("post","/trade/cointype",{size:20}, function(res) {
            var constr = "";
            for(const [i, v] of res.data.entries()){
                console.log( i,typeof v.vol,v.vol)
                constr += "<li>";
                constr += "<span class='span'>"+v.name+"</span>";
                constr += "<span class='span'>"+v.current_price_usd+"</span>";
                constr += "<span class='span'>"+v.vol+"</span>";
                if(v.change_percent > 0){
                    constr += "<span class='span1' style='color: #00FF00;'>"+v.change_percent+"%</span>";
                }else{
                    constr += "<span class='span1' style='color: #FF0000;'>"+v.change_percent+"%</span>";
                }
                var links = v.name.toLowerCase()+"_usdt";
                constr += '<span class="span2"><a href="/trade/index?type=trade&market='+links+'&lang=zh" style="color: #0A88DF;">去交易</a></span>';
                constr += "</li>";
            }
            $("#rec-list").html(constr);
        },"json");
    }
</script>
<style>
    #container {
        width: 100%;
        overflow: hidden;
        padding: 20px 10px 10px 10px;
        display: flex;
    }
    
    #container .boxCon {
        height: 120px;
        font-size: 14px;
        padding: 19px 16px;
        font-family: Adobe Heiti Std R;
        font-weight: 400;
        margin-bottom: 15px;
        margin-left: 0.5%;
        flex: 1;
    }
    
    #container .boxCon:first-child {
        margin-left: 0px;
    }
    
    #container .boxCon .amount .amountLeft {
        font-size: 20px;
    }
    
    #container .boxCon .amount .amountRight {
        color: #A8A4B5;
    }
    
    #container .boxCon .currency {
        margin-bottom: 6px;
    }
    
    #container .boxCon .currency .currencyLeft {
        color: #FFFFFF;
    }
    
    .actGreen {
        color: #03BF7B;
    }
    
    .actRed {
        color: #E44836;
    }
    
    @media screen and (max-width: 1366px) {
        body {
            background-color: lightblue;
        }
        #container .boxCon .amount .amountLeft {
            font-size: 14px;
        }
    }
    /* #container .boxCon */
</style>
<style>
    .listBox{
        background: url('/public/imgae/homeImg.png') no-repeat;
        background-size: 100% 100%;
        /*padding: 60px 0;*/
        padding: 30px 0 40px 0;
    }
    .content_ul{
        padding: 0 !important;
    }
    .content_ul .hide_div{
        padding: 0;
        border: none;
    }
    .rec-box .rec-con {
        margin: 10px 0;
        padding: 0;
        margin-top: 0;
    }
    .actoveUser{
        color: #0A88DF !important;
        border-bottom: 2px solid #0A88DF !important;
    }
    .rec-box .rec-con .rec-title{
        display: flex;
        justify-content: space-between;
        font-size: 14px;
        color: rgba(255,255,255,0.7);
        line-height: 1.5
    }
    .rec-box .rec-con .span{
        flex: 1;
        text-align: center;
        /*line-height: 3;*/
        height: 45px;
        line-height: 45px;
    }
    .rec-box .rec-con .span1 {
        flex: none;
        width: 350px;
        display: block;
        text-align: center;
        color: #8C8899;
        /*line-height: 3;*/
        height: 45px;
        line-height: 45px;
    }
    .rec-box .rec-con .span2 {
        flex: none;
        width: 150px;
        display: block;
        text-align: center;
        /*line-height: 3;*/
        height: 45px;
        line-height: 45px;
    }
    ul{
        list-style: none;
    }
    .ft12 {
        font-size: 12px;
    }
    .rec-box .rec-con .rec-title, .rec-box .rec-con li {
        display: flex;
        justify-content: space-between;
    }
    .rec-con ul li:nth-of-type(2n-1) {
        background: #0D101E !important;
        height: 45px;
        border: none;
    }
    .rec-box .rec-con li {
        font-size: 12px;
        color: #728daf;
        background: #131625;
        /*border-top: 1px solid #2e394c;*/
    }
    .useTitle .text{
        color: rgba(255,255,255,0.7);
        float: left;height: 95%;margin: 0 20px 10px 0;
        cursor: pointer;
    }
    /*rec-list*/
</style>