<!DOCTYPE html>
<html lang="en" style="background: #000000;">

<head>
    <meta charset="utf-8">
    <title><?=$system['system']?>-登录</title>
    <meta name="description" content="particles.js is a lightweight JavaScript library for creating particles.">
    <meta name="author" content="Vincent Garreau" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <!-- <link rel="stylesheet" media="screen" href="./login/style.css"> -->
    <link rel="stylesheet" href="/public/css/index.css">
    <link rel="stylesheet" href="/public/css/commonHead.css">
    <link rel="stylesheet" type="text/css" href="/public/css/login.css" />
</head>

<body>
    <!-- 主要内容 -->
    <div>
        <div class="fl" style="color: #FE6600;
            font-weight: bold;
            font-size: 26px;
            position: fixed;
            z-index: 999;
            top: 50px;
            left: 50px;
            cursor: pointer;" onclick="window.location.href='/'">
            <img src="<?=$system['logo']?>" class="navbar-logo" style="width: 88px; position: relative; top: -2px;">
        </div>
    </div>
    <!-- 定位box -->
    <div id="particles-js">

        <!-- 主要内容 -->
        <div>
            <div class="login1">
                <div class="title">
                    <div style="line-height: 35px;margin-bottom: 10px;"><?=$system['system']?> 登 录</div>
                    <div style="line-height: 35px;margin-bottom: 30px;font-size: 18px;">Exchange login</div>
                </div>
                <div class="login">
                    <h1 class="login-top" style="text-align: center;">
                        登录
                    </h1>
                    <div class="login-center clearfix">
                        <div class="login-center-img"><img src="/public/imgae/userImg.png" /></div>
                        <div class="login-center-input">
                            <input type="text" name="username" value="" class="tel" placeholder="请输入您的手机号" onfocus="this.placeholder=''" onblur="this.placeholder='请输入您的手机号'" />
<!--                            <div class="login-center-input-text">手机号</div>-->
                        </div>
                    </div>
                    <div class="login-center clearfix">
                        <div class="login-center-img"><img src="/public/imgae/passImg.png" /></div>
                        <div class="login-center-input">
                            <input type="password" class="pwd" name="password" value="" placeholder="请输入密码" onfocus="this.placeholder=''" onblur="this.placeholder='请输入您的密码'" />
<!--                            <div class="login-center-input-text">密码</div>-->
                        </div>
                    </div>
                    <div class="clearfix" style="margin: 0 40px 10px 40px;font-size: 16px;">
                        <div class="fl"><a style="color: #50BACC;" href="/index/register?lang=zh">注册账户</a></div>
                        <div class="fr"><a style="color: #FFFFFF;opacity: 0.7;" href="/index/forgetrassword?lang=zh">忘记密码</a></div>
                    </div>
                    <div class="login-button subbtn activeTap">登录</div>
                </div>
            </div>
        </div>
        <div class="sk-rotating-plane"></div>
    </div>
</body>

</html>
<script type="text/javascript" src="/public/js/public.js"></script>
<script type="text/javascript" src="/public/layer/jquery-1.9.1.min.js"></script>
<script type="text/javascript" src="/public/layer/layer.js"></script>
<script type="text/javascript">
    function hasClass(elem, cls) {
        cls = cls || '';
        if (cls.replace(/\s/g, '').length == 0) return false; //当cls没有参数时，返回false
        return new RegExp(' ' + cls + ' ').test(' ' + elem.className + ' ');
    }

    function addClass(ele, cls) {
        if (!hasClass(ele, cls)) {
            ele.className = ele.className == '' ? cls : ele.className + ' ' + cls;
        }
    }

    function removeClass(ele, cls) {
        if (hasClass(ele, cls)) {
            var newClass = ' ' + ele.className.replace(/[\t\r\n]/g, '') + ' ';
            while (newClass.indexOf(' ' + cls + ' ') >= 0) {
                newClass = newClass.replace(' ' + cls + ' ', ' ');
            }
            ele.className = newClass.replace(/^\s+|\s+$/g, '');
        }
    }
    document.querySelector(".subbtn").onclick = function() {
        var tel = document.querySelector(".tel").value;
        if (tel == "") {
            layer.msg('手机号不能为空');
            return false;
        }
        var pwd = document.querySelector(".pwd").value;
        if (pwd == "") {
            layer.msg('密码不能为空');
            return false;
        }
        ajax_http("post","/index/login",{tel:tel,password:pwd},function (msg) {
            if(msg == '登录成功'){
                layer.msg(msg);
                setTimeout(function () {
                    window.sessionStorage.status = 2;
                    window.location.href='/index/index?lang=zh';
                },1000);
            }else{
                window.sessionStorage.status = 1;
                layer.msg(msg);
            }
        });
    }
</script>
<style>
    input::-webkit-input-placeholder{
        color:#A8A4B5;
        opacity: 0.5;
    }
    input::-moz-placeholder{
        color:#A8A4B5;
        opacity: 0.5;
    }
    input:-moz-placeholder{
        color:#A8A4B5;
        opacity: 0.5;
    }
    input:-ms-input-placeholder{
        color:#A8A4B5;
        opacity: 0.5;
    }
    input {
        background-color: rgba(255, 255, 255, 0) !important;
        color: #fff;
    }
    input:-webkit-autofill {
        transition: background-color 5000s ease-in-out 0s;
        -webkit-text-fill-color: rgba(255,255,255,0.7) !important;
    }
    input:-webkit-autofill:focus {
        -webkit-text-fill-color: rgba(255,255,255,0.7) !important;
    }
</style>