

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>龙链 - 后台管理系统</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/public/layuiadmin/layui/css/layui.css" media="all">
</head>
<body>

<div class="layui-form" lay-filter="layuiadmin-form-role" id="layuiadmin-form-role" style="padding: 20px 30px 0 0;">
    <div class="layui-form-item">
        <label class="layui-form-label">帮助分类</label>
        <div class="layui-input-block">
            <select name="title">
                <option value="收款设置">收款设置</option>
                <option value="账户注册">账户注册</option>
                <option value="资产管理">资产管理</option>
                <option value="密码修改">密码修改</option>
                <option value="出售USDT">出售USDT</option>
                <option value="购买USDT">购买USDT</option>
                <option value="身份认证">身份认证</option>
                <option value="杠杆交易">杠杆交易</option>
            </select>
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">文章内容</label>
        <div class="layui-input-block">
            <textarea id="content" style="display: none;" name="content"></textarea>
        </div>
    </div>
    <div class="layui-form-item" style="float: right;">
        <button class="layui-btn" lay-submit lay-filter="LAY-user-role-submit" id="LAY-user-role-submit">提交</button>
        <button class="layui-btn" lay-reset lay-filter="LAY-user-role-close" id="LAY-user-role-close">取消</button>
    </div>
</div>

<script src="/public/layuiadmin/layui/layui.js"></script>
<script>
    layui.config({
        base: '/public/layuiadmin/' //静态资源所在路径
    }).extend({
        index: 'lib/index' //主入口模块
    }).use(['index', 'form','layedit'], function(){
        var $ = layui.$
            ,form = layui.form;
        var layedit = layui.layedit;
        layedit.set({uploadImage:{url:'/upload/edit',type:'post'}});
        var index = layedit.build('content',{hideTool:['face'], height: 250}); //建立编辑器
        var index2 = parent.layer.getFrameIndex(window.name); //获取窗口索引
        form.on("submit(LAY-user-role-submit)",function (data) {
            let jsonstr = {
                title:data.field.title,
                content:layedit.getContent(index)
            };
            $.post("/ajax/addnotice",jsonstr,function (msg) {
                if(msg == 1){
                    //发异步，把数据提交给php
                    layer.msg("添加帮助成功", {icon: 6}, function() {
                        //关闭当前frame
                        parent.layer.close(index2);
                        // 可以对父窗口进行刷新
                        parent.location.reload();
                    });
                }else if(msg == 2){
                    layer.msg("该帮助已经存在，请重新输入")
                }else{
                    layer.msg("添加帮助失败")
                }
            });
        });

        $("#LAY-user-role-close").on("click",function (data) {
            parent.layer.close(index2);
        });
    })
</script>
</body>
</html>