

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>龙链 - 后台管理系统</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/public/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/public/layuiadmin/style/admin.css" media="all">
</head>
<body>

<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-form layui-card-header layuiadmin-card-header-auto">
            <div class="layui-form-item">
                <div style="float: left;">
                    <div class="layui-inline">
                        <button class="layui-btn layuiadmin-btn-admin" data-type="add">添加</button>
                    </div>
                </div>
                <div style="float: right">
                    <div class="layui-inline">
                        <label class="layui-form-label">标题</label>
                        <div class="layui-input-block">
                            <input type="text" name="loginname" placeholder="请输入标题" autocomplete="off" class="layui-input">
                        </div>
                    </div>
                    <div class="layui-inline">
                        <button class="layui-btn layuiadmin-btn-admin" lay-submit lay-filter="LAY-user-back-search">
                            <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>

        <div class="layui-card-body">
            <table id="LAY-user-back-manage" lay-filter="LAY-user-back-manage"></table>

            <script type="text/html" id="table-useradmin-admin">
                <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del"><i class="layui-icon layui-icon-delete"></i>删除</a>
            </script>
        </div>
    </div>
</div>

<script src="/public/layuiadmin/layui/layui.js"></script>
<script>
    layui.config({base: '/public/layuiadmin/'}).extend({index: 'lib/index'}).use(['index', 'table',"layedit"], function(){
        var $ = layui.$
            ,form = layui.form
            ,table = layui.table;
        table.render({
            elem: "#LAY-user-back-manage",
            url: "/ajax/noticelist",
            cols: [[
                {type: "checkbox", fixed: "left"},
                {field: "id", width: 80, title: "ID", sort: !0},
                {field: "title", title: "标题"},
                {field: "content", title: "内容"},
                {title: "操作", width: 150, align: "center", fixed: "right", toolbar: "#table-useradmin-admin"}]
            ],
            text: "对不起，加载出现异常！"
        }),table.on("tool(LAY-user-back-manage)", function (e) {
            e.data;
            if ("del" === e.event) layer.prompt({formType: 1, title: "敏感操作，请验证口令"}, function (t, i) {
                layer.close(i), layer.confirm("确定删除此新闻？", function (t) {
                    console.log(e), e.del(), layer.close(t)
                })
            });
        });
        //监听搜索
        form.on('submit(LAY-user-back-search)', function(data){
            var field = data.field;
            //执行重载
            table.reload('LAY-user-back-manage', {
                where: field
            });
        });

        //事件
        var active = {
            add: function(){
                layer.open({type: 2,title:'添加新闻' ,content: '/adminhome/addnotice',area: ['800px', '520px']})
            }
        }
        $('.layui-btn.layuiadmin-btn-admin').on('click', function(){
            var type = $(this).data('type');
            active[type] ? active[type].call(this) : '';
        });
    });
</script>
</body>
</html>

