<!DOCTYPE html>
<html lang="en" class="no-js">
    <head>
        <meta charset="utf-8">
        <title>霸王交易所--代理商登录</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
        <!-- CSS -->
        <link rel="stylesheet" href="/public/css/reset.css">
        <link rel="stylesheet" href="/public/css/supersized.css">
        <link rel="stylesheet" href="/public/css/login_new.css">

    </head>
    <body class="loginbg">

        <div class="loginbk">
            <div class="titbg">龙链-代理商系统</div>
            <form action="/merc/login" method="post">
                <input type="text" name="username" autocomplete="off" class="username" placeholder="用户名" >
                <input type="password" name="password" autocomplete="off" class="password" placeholder="密码" >
                <button type="submit">登　　录</button>
                <div class="error"><span>+</span></div>
            </form>
        
        </div>
    </body>

</html>

