<!-- 侧边菜单 -->
<div class="layui-side layui-side-menu">
    <div class="layui-side-scroll">
        <div class="layui-logo" lay-href="/adminhome/console">
            <span>龙链</span>
        </div>

        <ul class="layui-nav layui-nav-tree" lay-shrink="all" id="LAY-system-side-menu" lay-filter="layadmin-system-side-menu">
            <li data-name="senior" class="layui-nav-item">
                <a lay-href="/merc/add" lay-tips="添加代理商" lay-direction="2">
                    <i class="layui-icon layui-icon-auz"></i><cite>添加代理商</cite>
                </a>
            </li>
            <li data-name="senior" class="layui-nav-item">
                <a lay-href="/merc/list" lay-tips="代理商列表" lay-direction="2">
                    <i class="layui-icon layui-icon-auz"></i><cite>代理商列表</cite>
                </a>
            </li>
            <li data-name="senior" class="layui-nav-item">
                <a lay-href="/merc/user" lay-tips="用户列表" lay-direction="2">
                    <i class="layui-icon layui-icon-auz"></i><cite>用户列表</cite>
                </a>
            </li>
            <li data-name="senior" class="layui-nav-item">
                <a lay-href="/merc/log" lay-tips="用户日志" lay-direction="2">
                    <i class="layui-icon layui-icon-auz"></i><cite>用户日志</cite>
                </a>
            </li>
        </ul>
    </div>
</div>