<!DOCTYPE html>
<html style="background: #010715;height: 100%;">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta data-n-head="true" data-hid="format-detection" name="format-detection" content="telephone=no">
    <meta data-n-head="true" http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta data-n-head="true" name="renderer" content="webkit">
    <title><?=$system['system']?>-新币预售</title>
    <link href="/public/css/index.css" rel="stylesheet">
    <link rel="stylesheet" href="/public/css/commonHead.css">
    <link rel="stylesheet" href="/public/css/newCoin.css">
</head>

<body class="scroll" style="background: #010715;height: 100%;">
    <div id="app">
        <div class="notice">
            <?php load_view("inc/nav");?>
            <div style="background:#010715;">

                <div class="box">
                    <!-- 投票列表 -->
                    <div class="list">
                        <div class="topcontent ft20 fColor1">
                            <span class="fl">新币预售</span>
                            <span class="fr isVote" style="cursor: pointer;">我的参与</span>
                        </div>
                        <ul class="list_issue">
                            <?php foreach ($result as $k=>$v): ?>
                            <li>
                                <a href="/activity/newcoindetails?type=newcoin&id=<?=$v['id']?>&lang=zh">
                                    <img class="coinimg" src="<?=$v['pic']?>" style="width: 125px; height: 125px; border-radius: 100px;">
                                    <h3 class="title tc bs" style="overflow: hidden;margin: 0 auto;width: 100%;">
                                        <span style="display: inline-block;float: left"><?=get_currency_name($v['currency_id'])?></span>
                                        <span style="display: inline-block;float: left">(</span>
                                        <span style="display: inline-block;float: left;width: 130px;white-space: nowrap;overflow: hidden;text-overflow: ellipsis;"><?=$v['title']?></span>
                                        <span style="display: inline-block;float: left">)</span>
                                    </h3>
                                    <div class="clearfix">
                                        <p class="describe tc bs fl">发行量：<?=$v['total_num']?><?=get_currency_name($v['currency_id'])?></p>
                                        <?php
                                        $time = time();
                                        $str = "";
                                        if($time < $v['start_time'] ){
                                            $str = '<p class="describe tc  fr" style="color: #00B3FF;">即将开启</p>';
                                        }else if($time >= $v['start_time'] && $time <= $v['end_time']){
                                            $str = '<p class="describe tc  fr" style="color: #00A000;">进行中</p>';
                                        }else{
                                            $str = '<p class="describe tc  fr" style="color: #E25657;">已结束</p>';
                                        }
                                        $scale = ($v['deal'] / $v['total_num']) * 100;
                                        ?>
                                        <?=$str?>
                                    </div>
                                    <div class="process-bar">
                                        <div class="process-bar-hover" style="width:<?=$scale?>%"></div>
                                    </div>
                                    <p class="part bs">
                                        <span class="fl" style="color: #535361;"><span style="color: #0AC38A;"><?=get_xbys_num($v['id'])?></span> 支持者</span>
                                        <span class="fr" style="color: #0AC38A;"><?=$scale?>%</span>
                                    </p>
                                </a>
                            </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                    <!-- 我的投票记录 -->
                    <div class="SettingRight" style="display: none;">
                        <div class="titles">
                            <h3 class="fl">我的参与</h3>
                            <span class="fr isRrturn" style="color: #fff;cursor: pointer;">&lt;&lt;返回</span>
                        </div>
                        <div class="Column_LogonLog">
                            <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                <tbody>
                                    <tr class="title" style="height: 45px;line-height: 45px;background: #202641;color: hsla(0,0%,100%,.3);">
                                        <th class="bor-but" width="">项目名称</th>
                                        <th class="bor-but" width="">币种</th>
                                        <th class="bor-but" width="">单价</th>
                                        <th class="bor-but" width="">数量</th>
                                        <th class="bor-but" width="">支付总额</th>
                                        <th class="bor-but" width="">解冻间隔</th>
                                        <th class="bor-but" width="">参与时间</th>
                                        <th class="bor-but" width="">解冻状态</th>
                                        <th class="bor-but" width="">上次解冻</th>
                                        <th class="bor-but" width="">状态</th>
                                        <th class="bor-but" width="">操作</th>
                                    </tr>
                                    <?php foreach($user_log as $k=>$v): ?>
                                    <tr class="title">
                                        <th width=""><?=$v['title']?></th>
                                        <th width=""><?=$v['currency_name']?></th>
                                        <th width=""><?=$v['price']?> <?=$v['x_currency_name']?></th>
                                        <th width=""><?=$v['num']?></th>
                                        <th width=""><?=$v['num']*$v['price']?> <?=$v['x_currency_name']?></th>
                                        <th width=""><?=$v['financial_cycle']?> <?=$v['time_type']?></th>
                                        <th width=""><?=date("Y-m-d H:i:s",$v['create_time'])?></th>
                                        <th width=""><?=$v['unfreeze']?>/<?=$v['freeze_status']?></th>
                                        <th width=""><?=date("Y-m-d H:i:s",$v['freeze_time'])?></th>
                                        <th width=""><?=($v['freeze_status'] == $v['unfreeze'])?"完成":"<span style='color: #00A000'>解冻中</span>"?></th>
                                        <th width="">立即解冻</th>
                                    </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="layui-layer-move"></div>
</body>

</html>
<script type="text/javascript" src="/public/layer/jquery-1.9.1.min.js"></script>
<script type="text/javascript" src="/public/layer/layer.js"></script>
<script type="text/javascript">
    $(function() {
        // 点击背景关闭
        $(".contentBack").click(function() {
            $(".box-back").hide();
            $(".contentBack").hide();
        });
        // 点击投票
        $(".opens").click(function() {
            var index = $(this).attr("data-index");
            console.log(index);
            $(".box-back").hide();
            $(".contentBack").hide();
        });
        // 点击xx
        $(".closeCharge").click(function() {
            $(".box-back").hide();
            $(".contentBack").hide();
        });
        $("#btn").click(function() {
            var support_type = $("#support_type").val(); //支持还是反对
            var licai_num = $("#licai_num").val(); //票数
            var paypassword = $("#paypassword").val(); //支持还是反对
            if (support_type == '') {
                layer.msg("支持还是反对不能为空");
                return
            } else if (licai_num == '') {
                layer.msg("票数不能为空");
                return
            } else if (paypassword == '') {
                layer.msg("交易密码不能为空");
                return
            }
            //发起请求-成功-隐藏--    $(".box-back").hide(); $(".contentBack").hide();

        });
        // 显示详情
        $(".isVote").click(function() {
            $(".list").hide();
            $(".SettingRight").show();
        });
        // 显示详情
        $(".isRrturn").click(function() {
            $(".list").show();
            $(".SettingRight").hide();
        });

    });
</script>